<a href="https://colab.research.google.com/github/swethachamala592/SVREC-WEBSITE/blob/main/training1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
numpy.__version__


'2.0.2'

In [ ]:
import numpy as np


In [ ]:
np.add(1,1)

np.int64(2)

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])

<class 'numpy.ndarray'>
(3,)
1 2 3


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
1 2 4


In [ ]:
import numpy as np
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [ ]:
c=np.full((2,2),4)
print(c)
d=np.eye(2)
print(d)

[[4 4]
 [4 4]]
[[1. 0.]
 [0. 1.]]


In [ ]:
e=np.random.random((3,3))
print(e)

[[0.12570979 0.73838765 0.87760548]
 [0.53127661 0.95228231 0.95276999]
 [0.36012154 0.71962898 0.63945963]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[3])



4


In [ ]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("2nd element from first row:",arr2[0,1])
print(arr2[2,3])

2nd element from first row: 2
14


In [ ]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# new=ar.reshape(4,3)
new=ar.reshape(2,3,2)
print(new)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
new1=a.reshape(-1)
print(new1)

[1 2 3 4 5 6]


In [ ]:
arrr=np.array([1,2,3])
for x in arrr:
  print(x)

1
2
3


In [ ]:
arrr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,21,12]],[[32,72,68],[92,50,20]]])
for x in arrr:
  # print(x)
  for j in x:
    # print(j)
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9
10
21
12
32
72
68
92
50
20


In [ ]:
b1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for

1
2
3
4
5
6
7
8
